server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: "ms_usuarios_boton"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "local"
  data:
    mongodb:
      uri: ${DB_URL}
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    producer:
      bootstrap-servers: broker:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: transaction-topic
    admin:
      properties:
        bootstrap:
          servers: broker:9092

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
